// var emails = [["abrahamrinifr@gmail.com","cl8gsweo"],
// ["adnansl_007@yahoo.com.in","f70v8l94"],
// ["lahothideepika@gmail.com","n46bmlsk"],
// ["prcsreddy6662@gmail.com","1hxrdftu"],
// ["mathperfecteducation@gmail.com","ef4mvi41"],
// ["uafausti@gmail.com","qmx1gr7q"],
// ["thakurmanisha331@gmail.com","2xrpjmsk"],
// ["Ashfiya.yazdani@gmail.com","f8cvq63r"],
// ["Sowjanya.g@globalindianschool.org","j0dafzg4"],
// ["archanakul06@gmail.com","3s5qi8oo"],
// ["arnazparakh@yahoo.com","swf0y703"],
// ["kirti1997choudhary@gmail.com","uc7nnhjr"],
// ["narendayadav68@gmail.com","r5h6agq8"],
// ["Gunjanchaudhary917@gmail.com","uyp3b303"],
// ["ritusheoran1000@gmail.com","4gkn4srk"],
// ["sanauddinmd@gmail.com","ynssywp1"],
// ["tsesikala@gmail.com","9m08u81l"],
// ["preetijagota@dpsrkp.net","jqpo7mft"],
// ["Charvinayyar@dpsrkp.net","n9xop6zd"],
// ["Nidhikatyal@dpsrkp.net","atstnzgm"],
// ["manishjain@dpsrkp.net","wi8jp35h"],
// ["swastiarya@dpsrkp.net","c26ri2ch"],
// ["Srishtisahrawat@dpsrkp.net","wk6itayo"],
// ["Yashikaarora@dpsrkp.net","bpftpwke"],
// ["kanikachamoli@dpsrkp.net","r91rf638"],
// ["triptikapoor@dpsrkp.net","pkydi7fb"],
// ["nehajuyal@dpsrkp.net","ubhsy4ny"],
// ["Nalinigautam@dpsrkp.net","nvk9ty4u"],
// ["priyaobhrai@dpsrkp.net","ycs0x5jm"],
// ["deekshagupta@dpsrkp.net","ykt214cm"],
// ["Priyamsharma@dpsrkp.net","9kh6rou8"],
// ["priyankayadav@dpsrkp.net","i5iwkepp"],
// ["nupoorsethi@dpsrkp.net","7p19v5vk"],
// ["randeepsingh@dpsrkp.net","ad6l88vd"],
// ["Madhuchaudhary@dpsrkp.net","462v1hgp"],
// ["azrataj1010@gmail.com","b8w5ebqw"],
// ["Sakshimalik@dpsrkp.net","jxzfayl4"],
// ["sumita.dore@gmail.com","h0jn2d8o"],
// ["anitaysingh@gmail.com","azzct7wq"],
// ["priyasano@gmail.com","2x7jivjk"],
// ["evfausti@yahoo.com","6e8i1hbf"]];

// var emailAndPws = emails.forEach((email) =>
//   console.log(`["${email}","${Math.random().toString(36).slice(-8)}"],`)
// );

// console.log(emailAndPws);
