import { Subject } from '@/types';
export const DEV_PORT = 3000;
export const PRODUCT_NAME = 'AssistTeacher';
export const subjects: Subject[] = [
  'English',
  'Math',
  'Social',
  'Science',
  'EVS',
  'Chemistry',
  'Physics',
  'Biology',
  'ICT',
  'History',
  'Geography',
  'Civics',
];
export const grades = [
  '1st',
  '2nd',
  '3rd',
  '4th',
  '5th',
  '6th',
  '7th',
  '8th',
  '9th',
  '10th',
  '11th',
  '12th',
];

export const defaultSubjects = {
  Nursery: ['English', 'Maths', 'EVS'],
  LKG: ['English', 'Maths', 'EVS'],
  UKG: ['English', 'Maths', 'EVS'],
  'Class 1': ['English', 'Hindi', 'Maths', 'EVS', 'Computer Studies'],
  'Class 2': ['English', 'Hindi', 'Maths', 'EVS', 'Computer Studies'],
  'Class 3': ['English', 'Hindi', 'Maths', 'EVS', 'Computer Studies'],
  'Class 4': ['English', 'Hindi', 'Maths', 'EVS', 'Computer Studies'],
  'Class 5': ['English', 'Hindi', 'Maths', 'EVS', 'Computer Studies'],
  'Class 6': [
    'English',
    'Hindi',
    'Maths',
    'History & Civics',
    'Geography',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Studies',
  ],
  'Class 7': [
    'English',
    'Hindi',
    'Maths',
    'History & Civics',
    'Geography',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Studies',
  ],
  'Class 8': [
    'English',
    'Hindi',
    'Maths',
    'History & Civics',
    'Geography',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Studies',
  ],
  'Class 9': [
    'English',
    'Hindi',
    'Maths',
    'History & Civics',
    'Geography',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Applications',
  ],
  'Class 10': [
    'English',
    'Hindi',
    'Maths',
    'History & Civics',
    'Geography',
    'Physics',
    'Chemistry',
    'Biology',
    'Computer Applications',
  ],
  'Class 11': [
    'English',
    'Physics',
    'Chemistry',
    'Biology',
    'Maths',
    'Computer Science',
    'Economics',
  ],
  'Class 12': [
    'English',
    'Physics',
    'Chemistry',
    'Biology',
    'Maths',
    'Computer Science',
    'Economics',
  ],
};
